gp:
  num_individuals: 10 #2000
  generations: 10
  multi_island:
    num_islands: 1
    migration: { "freq": 10, "frac": 0.05 }
  crossover_prob: 0.2
  mut_prob: 0.8
  frac_elitist: 0
  min_height: 2
  max_height: 5
  overlapping_generation: True
  validate: True
  penalty: { "method": "length", "reg_param": 0.1 }
  select:
    fun: tools.selection.tournament_with_elitism
    kargs: "{'tournsize': 2, 'stochastic_tourn': { 'enabled': True, 'prob': [0.7, 0.3] }}"
  mutate:
    fun: gp.mixedMutate
    # fun: gp.mutNodeReplacement
    # fun: gp.mutInsert
    # fun: gp.mutShrink
    kargs: "{'expr': toolbox.expr_mut, 'pset': pset, 'prob': [0.8, 0.2, 0.]}" # string is important
    expr_mut: gp.genHalfAndHalf
    expr_mut_kargs: "{'min_': 1, 'max_': 3}"
  crossover:
    fun: gp.cxOnePoint
    kargs: "{}"
  immigration: { "enabled": False, "freq": 10, "frac": 0.9 }
  primitives:
    imports: { "flex.gp.cochain_primitives": ["coch_primitives"],
              "flex.gp.jax_primitives": ["jax_primitives"]}
    used:
       [
      {"name": "AddF", "dimension": None, "rank": None},
      {"name": "SubF", "dimension": None, "rank": None},
      {"name": "MulF", "dimension": None, "rank": None},
      {"name": "Div", "dimension": None, "rank": None},
      {"name": "SquareF", "dimension": None, "rank": None},
      {"name": "SqrtF", "dimension": None, "rank": None},
      {"name": "AddC", "dimension": ["0", "1", "2"], "rank": ["SC", "T"]},
      {"name": "SubC", "dimension": ["0", "1", "2"], "rank": ["SC", "T"]},
      {"name": "Square", "dimension": ["0", "1", "2"], "rank": ["SC", "T"]},
      {"name": "Sqrt", "dimension": ["0", "1", "2"], "rank": ["SC", "T"]},
      {"name": "tr", "dimension": ["0", "1", "2"], "rank": ["T"]},
      {"name": "MF", "dimension": ["0", "1", "2"], "rank": ["T"]},
      {"name": "tran", "dimension": ["0", "1", "2"], "rank": ["T"]},
      {"name": "sym", "dimension": ["0", "1", "2"], "rank": ["T"]},
      {"name": "St", "dimension": ["0", "1", "2"], "rank": ["T"]},
      {"name": "Inn", "dimension": ["0", "1", "2"], "rank": ["T"]}
    ]
  residual_formulation: False
  batch_size: 1
  plot_best: True
